apiVersion: v1
kind: DNS
metadata:
  name: nginx-dns
spec:
  rules:
    - host: myservice.com
      paths:
        - path: /service1
          backend:
            service:
              name: nginx-service
              port: 801
        - path: /service2
          backend:
            service:
              name: nginx-service-2
              port: 802
